const { teste, app, bancoNovo, reabrirBanco, assert, novaPasta, FIXTURES } = global.ctx
const fs = require('fs')
const { DatabaseSync } = require('node:sqlite')
const path = require('path')

// schema de antes da aba Alimentação, congelado em tests/fixtures (não depende do git)
function schemaAntigo() {
  const sql = fs.readFileSync(path.join(FIXTURES, 'schema-antes-alimentacao.sql'), 'utf8')
  return sql
    .split(/\r?\n/)
    .filter(l => !l.startsWith('--'))
    .join('\n')
    .split(';')
    .map(s => s.trim())
    .filter(Boolean)
}

teste('regressão: banco da versão anterior (com dados) abre na versão nova sem perder nada', async () => {
  const dir = novaPasta('chama-antigo-')
  const antigo = new DatabaseSync(path.join(dir, 'chama.db'))
  const sqls = schemaAntigo()
  assert.ok(sqls.length >= 7 && !sqls.some(s => /alimentos_taco|refeicoes/.test(s)))
  for (const s of sqls) antigo.exec(s)
  antigo.exec(`INSERT INTO habitos (nome, emoji, frequencia_tipo, tipo) VALUES ('academia', '💪', 'diario', 'academia')`)
  antigo.exec(`INSERT INTO registros_diarios (habito_id, data, feito) VALUES (1, '2026-09-27', 1)`)
  antigo.exec(`INSERT INTO metas_semestrais (nome, tipo, valor_alvo, data_inicio, data_fim) VALUES ('guardar', 'financeiro', 1000, '2026-07-01', '2026-12-31')`)
  antigo.exec(`INSERT INTO config (chave, valor) VALUES ('lembrete_ativo', '1'), ('horario_lembrete', '21:30')`)
  antigo.exec(`INSERT INTO treinos (nome) VALUES ('Superiores')`)
  antigo.exec(`INSERT INTO treino_exercicios (treino_id, nome, grupo) VALUES (1, 'Supino', 'peito')`)
  antigo.close()

  await reabrirBanco(dir)
  const db = app('src/db/database.js').getBanco()
  assert.equal((await db.getFirstAsync('SELECT COUNT(*) AS n FROM alimentos_taco')).n, 597)
  assert.deepEqual(await db.getAllAsync('SELECT nome, emoji, tipo FROM habitos'), [{ nome: 'academia', emoji: '💪', tipo: 'academia' }])
  assert.equal((await db.getFirstAsync('SELECT COUNT(*) AS n FROM registros_diarios')).n, 1)
  assert.equal((await db.getFirstAsync('SELECT nome FROM metas_semestrais')).nome, 'guardar')
  const config = app('src/db/config.js')
  assert.equal(await config.buscarConfig('lembrete_ativo'), '1')
  assert.equal(await config.buscarConfig('horario_lembrete'), '21:30')
  assert.equal(await config.buscarConfig('taco_versao'), '1')
  const treinos = app('src/db/treinos.js')
  assert.deepEqual((await treinos.buscarTreinos()).map(t => t.nome), ['Superiores'])
  assert.deepEqual((await treinos.buscarExerciciosDoTreino(1)).map(e => e.nome), ['Supino'])
  assert.deepEqual(await app('src/db/refeicoes.js').listarRefeicoesDoDia(), [])

  // e reabrir de novo continua igual (sem reimportar, sem duplicar)
  await reabrirBanco(dir)
  const db2 = app('src/db/database.js').getBanco()
  assert.equal((await db2.getFirstAsync('SELECT COUNT(*) AS n FROM alimentos_taco')).n, 597)
  assert.equal((await db2.getFirstAsync('SELECT COUNT(*) AS n FROM habitos')).n, 1)
})

teste('regressão: hábitos, registros, metas, treinos e config seguem funcionando', async () => {
  await bancoNovo()
  const { hojeISO } = app('src/utils/data.js')
  const habitos = app('src/db/habitos.js')
  const registros = app('src/db/registros.js')
  const metas = app('src/db/metas.js')
  const treinos = app('src/db/treinos.js')
  const config = app('src/db/config.js')

  await habitos.criarHabito('ler', '📚', 'estudo', 'diario', null, hojeISO())
  const [h] = await habitos.buscarHabitosAtivos()
  assert.equal(h.nome, 'ler')
  await registros.marcarHabito(h.id, hojeISO())
  assert.equal(await registros.contarHabitosConcluidos(), 1)
  assert.ok((await registros.calcularStreak()) >= 1)
  await registros.desmarcarHabito(h.id, hojeISO())
  assert.equal(await registros.contarHabitosConcluidos(), 0)

  await metas.criarMeta('correr', 'saude', '🏃', 100, 'km', '2026-07-01', '2026-12-31')
  const [m] = await metas.buscarMetas()
  await metas.registrarProgresso(m.id, hojeISO(), 100)
  assert.equal(await metas.contarMetasConcluidas(), 1)

  await treinos.criarTreino('Inferiores')
  const [t] = await treinos.buscarTreinos()
  await treinos.adicionarExercicio(t.id, 'Agachamento', 'pernas')
  assert.equal((await treinos.buscarExerciciosDoTreino(t.id)).length, 1)
  await treinos.excluirTreino(t.id)
  assert.equal((await treinos.buscarTreinos()).length, 0)

  await config.salvarConfig('x', '1')
  await config.salvarConfig('x', '2')
  assert.equal(await config.buscarConfig('x'), '2')
})
